### PR TITLE
 🐛Display clearlogo in Music OSD only when enabled in skin settings

### LINKED ISSUE #231: :bug: Music OSD always displays Clearlogo if available
### Skin section

Other

### Current Behavior

Since commit 4ece9a9 I've noticed that the Music OSD always displays the Clearlogo for the artist (if available) rather than the name in text, irrespective of the setting Interface / Style - Title being Text or Logo. Having read thru discussion #186 I thought this was the intention, but I mat be wrong!

### Expected Behavior

Music OSD should be consistent with the Interface / Style - Title setting

### Steps To Reproduce

Play track for artist with Clearlogo

### Screenshots and Additional Info

_No response_

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

### PR DESCRIPTION
**Pull request by OfficerKD637**
Resolves https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/231

### CODE REVIEW

**Comment by OfficerKD637** [comment]
I am a dummy and don't know how to merge both the commits (should have been one commit in the first place🤦) 
Sorry Jurial!

**Comment by jurialmunkey** [comment]
On CLI `git rebase -i HEAD~2` does an interactive rebase of last two commits. 

In the interactive mode you simply change the commits on top of the one you want from `pick` to `squash` to squash them down into the "picked" one. Finally `git push origin +omega` force pushes to update the PR (force is needed since history diverged).

https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

It doesn't really matter anyway as I can squash directly from github.

**Comment by jurialmunkey** [comment]
BTW not necessary, but if I've got an on/off condition like this I'll just square bracket it and add the not `!` rather than try to figure out the inverse condition

e.g. 
```
String.IsEmpty($PARAM[top_logo]) | !Skin.HasSetting(TMDbHelper.EnableCrop)
![String.IsEmpty($PARAM[top_logo]) | !Skin.HasSetting(TMDbHelper.EnableCrop)]
```

or you can do it the other way around 
```
![!String.IsEmpty($PARAM[top_logo]) + Skin.HasSetting(TMDbHelper.EnableCrop)]
!String.IsEmpty($PARAM[top_logo]) + Skin.HasSetting(TMDbHelper.EnableCrop)
```

**Comment by OfficerKD637** [comment]
Woahh! Thank you so much Jurial!! I need to familiarize myself more with CLI because that sounds like a gamechanger! I've been using the GitHub desktop app since it has an approachable GUI for plebs like me lol!

And for the condition, that's such a useful tip! 
But I imagined I would need the AND condition for the clearlogo but OR for the title text so I didn't use the same condition with !.

Here's what I understood:
- The clearlogo needs both conditions to be true simultaneously so it uses AND

- But the title text acts as a fallback when there is no clearlogo present (even when title is set to 'crop' in the skin settings)
  And also needs to display text when the title is set to 'text' (even if clearlogo is present), hence it has to be OR

Did I get the logic right? I'm trying to get better at using the operators haha.

**Comment by jurialmunkey** [comment]
I expect the desktop github app can do a rebase too (it's a pretty core git feature), I just don't know myself since i only use git via cli

The two sets of conditions I posted above are identical to each other. A not condition always is the inverse 
ie `![true]` is the same as `false` 
and `![false]` is same as `true`

If the conditions in the brackets ultimately end up as true then not true is false.

**Comment by jurialmunkey** [comment]
Think of it this way:

`True | false = true`
`True + false = false`
So
`![true | false] = false`
`![true + false] = true`

Or to use a real world thing, suppose we're playing a game of 20 questions and the answer is "a tree"

If I ask "is it a plant OR an animal" you would say true (trees are plants).
If I ask "is it a plant AND an animal" you would say false (trees are not animals).


i.e.
```
tree=plant OR tree=animal == true
tree=plant AND tree=animal == NOT(true) == false
```


so
```
NOT(tree=plant OR tree=animal) == NOT(true) == false
NOT(tree=plant AND tree=animal) == NOT(NOT true) == NOT(false) == true
```

**Comment by OfficerKD637** [comment]
Wow!! You explain these concepts so nicely that it makes it very easy  to wrap my head around it!
Man I wish I knew you during college.... I would have turned out so much smarter!

**Pull request merged**
