### PR TITLE
✨Bold episode titles in plot for better visual differentiation

### PR DESCRIPTION
**Pull request by OfficerKD637**
Added bold tags to the episode titles in the plot for better visual differentiation

Got this idea from the forum.

### CODE REVIEW

**Comment by jurialmunkey** [comment]
I appreciate taking the time to PR it, but I'm not particularly keen on it.

I had something similar in early versions of AF1. The problem with inline bold tags is that it is not true bold. Kodi just increases the stroke width. This leads to bad rendering of some characters (especially with Arabic and CJK) and inconsistency in the font.

The other issue is that it will cause inconsistencies in other areas such as the plot dialog, where bold is already used for headings.

You'll also note that in general bold is only ever used with the brighter 90% colour definition `main_fg_90` not the 70% `main_fg_70` used for standard weight text.

Side note, but if you are editing skin variables files, you should not be editing the output file. You need to edit the template file `skinvariables-labels.xml` then you regenerate the output with the command
`runscript(script.skinvariables,action=buildvars,template=labels,force)`

If you only edit the output, it will be overwritten the next time the script regenerates the file (and more importantly you're giving yourself way too much work to do it all by hand when that's the point of the script to handle it for you!).

**Comment by OfficerKD637** [comment]
Thank you so much for taking the time to explain all of this! I always get to learn something new from you! You've got such a knack for teaching and I think you should consider launching an online course on 'Kodi Skinning' haha.

And I'm so sorry I missed the launch of AF2. Life got a bit busy lol. But I see the community is already bustling!! I have been moving my fonts and other mods from AF1 and it's been such a smooth experience! This is so awesome! 

I also wanted to know your thoughts on a different PR I was about to send.

Currently, all addon and non-library playable items use the 'WEB' tag (and 'INFO' for TV Shows). Do you think it'd be cool to replace it with 'MOVIE', 'EPISODE', 'SEASON', 'TV' and 'VIDEO'?

This could be handy when browsing mixed widgets or lists (like the 'Both' list in the Discover hub on AF1 or something like a combined Skin Variables 'Watchlist' widget or 'In Progress' with movies, TV shows and episodes).

Let me know what you think!

And as always, thank you so much for everything! I truly appreciate it!

**Comment by jurialmunkey** [comment]
> Currently, all addon and non-library playable items use the 'WEB' tag (and 'INFO' for TV Shows). Do you think it'd be cool to replace it with 'MOVIE', 'EPISODE', 'SEASON', 'TV' and 'VIDEO'?

I think the main issue you'd run into is the sizing. 

At the moment all the HD/FHD/4K/WEB/INFO/Collection Icon are all the same width to avoid pushing the info line across.

If you used DBType, I think the sizing changing could be annoying for mixed content.

Also note that it doesn't just say "WEB". It says the resolution of the video for local files. In my library, for example, I have a mix of local files and strm files (linked to TMDbHelper) -- at the moment a local movie (4K) and a TMDbHelper movie (WEB) will use the same size button, but if these are dbtypes instead of WEB then it will no longer be the same size and it'd be fairly annoying while scrolling (or alternatively the button would need to be very wide which would look odd for such a small label as 4K).

**Comment by OfficerKD637** [comment]
Haha yeah I know. I'm sorry I should've clarified that all addon and **_non_**-library playable items (basically using String.IsEmpty($PARAM[container]ListItem.VideoResolution) as the condition)

For the sizing issue, I am using width=64 for all the resolution tags, INFO tag and the TV tag
For the longer terms (MOVIE, EPISODE, SEASON and VIDEO) I am using width=100
I think the 36px jump might not be too visually unappealing? Definitely let me know what you think.

I have also added some OR conditions to take Container(99950) into account when switching between the focused item and the sidemenu buttons. This will prevent switching back and forth between INFO and the other tags.

I think ListItem.VideoResolution doesn't work with Container(99950) so the switching between INFO and the resolution tags can't be avoided.

I have a working code but I haven't tested it too extensively. It doesn't break any other parts of the skin like the VideoOSD (famous last words, ha). But let me know how you feel about this:
https://pastebin.com/xArxRBTR

P.S. The reason I have `String.IsEmpty($PARAM[container]ListItem.HdrType)` is because I have a custom HDR tag in the info line. You can ignore that.

**Comment by jurialmunkey** [comment]
>  I think the 36px jump might not be too visually unappealing? Definitely let me know what you think.

Have you tested it with "Boxes" disabled? I think if you're testing it with infoline style as boxes, it is probably not too annoying. But I think with the text mode (which is the default) the jumpiness could be a bit more irritating. 

Pay attention in particular to the premiere date label while scrolling.

With boxes on it isn't a big deal the changing width because that font doesn't have monospaced numbers. But with Text instead, the Roboto font does have monospaced numbers, so when you scroll the premiere date stays in a fixed position and only the numbers change -- I could see it becoming annoying if it starts shifting position.

**Comment by OfficerKD637** [comment]
Here's a quick video with Infoline set to 'Text' and using the Default font
https://streamable.com/7jvt6z

Definitely not 'perfect', but since there's always a bit of jumping with the other info line items (like Genre, End Time, etc.) due to the service monitor, I think this one's fine and I just chalk it up to something that's not unreasonable haha.

I'm just eyeballing everything and don't know the right way of technically testing this, so please take everything I say with a (huge) pinch of salt.

**Comment by OfficerKD637** [comment]
Hey @jurialmunkey !

Hope you're doing well!

Sorry to bother you again.

Did you have a chance to check out the video above? Do you think the added tags are worth the tradeoff of the premiered date shifting? If yes, I can send in the PR. If not, then I can close this (or GitHub will keep adding all subsequent commits to this PR)

On a similar note, do you think it'd be possible to add some new properties to TMDbHelper?
Since you already have incorporated the 'Get additional details from Kodi database' setting, I feel ListItem.VideoResolution, HdrType, etc. (I have a [similar request](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/1263) open on the TMDbH page regarding TotalSeasons and TotalEpisodes) would be very helpful to use alongside Container(99950). This would prevent the switching between the 4K/FHD/HD/SD/WEB tags and the INFO tag when the control moves focus from the widgets to the sidemenu. 

Let me know what you think!

Thank you!

**Comment by jurialmunkey** [comment]
> Did you have a chance to check out the video above? 

In the video it looks okay just going back and forth between the two items, but once you start scrolling across several items it is less great. I'm still on the fence about it.

> Since you already have incorporated the 'Get additional details from Kodi database' setting, I feel ListItem.VideoResolution, HdrType, etc. 

Stream details are stored in a separate table in the Kodi DB. 
These are indexed according to filepath, not DBID, so are not suitable or relevant to retrieve in TMDbHelper where we are getting details according to ID, not details about a specific file.

And being a separate table means a separate lookup, which means more lag.

**Comment by OfficerKD637** [comment]
> In the video it looks okay just going back and forth between the two items, but once you start scrolling across several items it is less great. I'm still on the fence about it.
> 

Yeah now that I think about it, it makes sense. I have always used 'Boxes' but I'm sure the 'Text' users would find this a bit annoying. Thanks for taking a look!

> Stream details are stored in a separate table in the Kodi DB. These are indexed according to filepath, not DBID, so are not suitable or relevant to retrieve in TMDbHelper where we are getting details according to ID, not details about a specific file.
> 
> And being a separate table means a separate lookup, which means more lag.

Wow I didn't know this! Definitely not worth the hit to the performance then. Thank you for letting me know.

I might keep this PR open for a few more days in case I have any more silly ideas to share with you haha.
Like I recently added a couple of separate conditions for 'Premiered' and 'Anticipated' in the status line to allow more differentiation between Returning Series 
_(I also loved having the days instead of exact dates so I copied them over from AF1. They felt so user-friendly and something that I had never seen in any other skin. The days_until_aired and since_aired were game changers! But I am well aware that the majority of the community prefers exact dates haha)._  

```
<!-- Premiered -->
		<value condition="[String.IsEqual(Container(99950).ListItem.Property(Status),Returning Series) | String.IsEqual(Container(99950).ListItem.Status,Returning Series)] + String.IsEmpty(Container(99950).ListItem.Property(Next_Aired)) + Integer.IsEqual(Container(99950).ListItem.Property(Last_Aired.Season),1) + Integer.IsLess(Container(99950).ListItem.Property(Last_Aired.Days_From_Aired),7) + String.IsEqual(Container(99950).ListItem.Property(Last_Aired),Container(99950).ListItem.Premiered)">$LOCALIZE[20473]</value>
```

```
<!-- Anticipated/Returning TBC -->
		<value condition="[String.IsEqual(Container(99950).ListItem.Property(Status),Returning Series) | String.IsEqual(Container(99950).ListItem.Status,Returning Series)] + String.IsEmpty(Container(99950).ListItem.Property(Next_Aired)) + Integer.IsLess(Container(99950).ListItem.Property(Last_Aired.Season),Container(99950).ListItem.Season)">$LOCALIZE[31543]</value>
```
If ListItem.Property(TotalSeasons) is something that can be retrieved via the ID (like you mentioned), it'd be awesome! I would love to use that instead of ListItem.Season.

Thank you for your time!

**Pull request closed without merging**
